In [1]:
# 6. DataFrame in Pandas

In [2]:
import pandas as pd

In [3]:
info = {
    "Name": ["Cipher", "Mind", "Cipher Mind"],
    "Marks": [98, 96, 92],
    "CGPA": [9.8, 9.6, 9.2]
}

print(info)

{'Name': ['Cipher', 'Mind', 'Cipher Mind'], 'Marks': [98, 96, 92], 'CGPA': [9.8, 9.6, 9.2]}

In [4]:
# Method - 1 Dictionary of List

df = pd.DataFrame(info)

print(type(df))

df

<class 'pandas.core.frame.DataFrame'>

          Name  Marks  CGPA
0       Cipher     98   9.8
1         Mind     96   9.6
2  Cipher Mind     92   9.2

In [5]:
print(df.index)

RangeIndex(start=0, stop=3, step=1)

In [6]:
print(df.columns)

Index(['Name', 'Marks', 'CGPA'], dtype='object')

In [11]:
# Method - 2 DataFrame as List of Lists

df = pd.DataFrame([["Cipher", 26], ["Mind", 16], ["Cipher Mind", 28]], columns = ["Name", "Age"])

df

          Name  Age
0       Cipher   26
1         Mind   16
2  Cipher Mind   28

In [16]:
# Method - 3 numpy array

import numpy as np

numpy_array = np.array([["Cipher", 26], ["Mind", 16], ["Cipher Mind", 28]])

numpy_array

df = pd.DataFrame(numpy_array, columns = ["Name", "Age"])

df

          Name Age
0       Cipher  26
1         Mind  16
2  Cipher Mind  28