In [1]:
# 10. Indexing & Selecting data

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("globalAirQuality.csv")

df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [4]:
# 1. Select Columns
df["country"]

0        US
1        US
2        US
3        US
4        US
         ..
17995    CH
17996    CH
17997    CH
17998    CH
17999    CH
Name: country, Length: 18000, dtype: object

In [5]:
df[["country", "city"]]

      country      city
0          US  New York
1          US  New York
2          US  New York
3          US  New York
4          US  New York
...       ...       ...
17995      CH    Zurich
17996      CH    Zurich
17997      CH    Zurich
17998      CH    Zurich
17999      CH    Zurich

[18000 rows x 2 columns]

In [6]:
# 2. Select Rows (Label & Index based) - loc & iloc
df.loc[3]

timestamp      2025-11-04 21:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                               30.403
pm10                               79.951
no2                                63.536
so2                                 7.609
o3                                 31.369
co                                   0.23
aqi                                   158
temperature                         23.14
humidity                           89.153
wind_speed                          8.956
Name: 3, dtype: object

In [7]:
df.loc[3:18] # starting idx : Ending idx ("Inclusive")

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
5,2025-11-04 23:25:17.554219,US,New York,40.713,-74.006,31.242,92.779,30.633,8.030,43.725,0.347,92,15.159,42.505,1.199
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
8,2025-11-05 02:25:17.554219,US,New York,40.713,-74.006,60.914,44.775,40.936,6.779,36.751,1.014,121,24.092,48.148,8.686
9,2025-11-05 03:25:17.554219,US,New York,40.713,-74.006,16.464,76.631,28.119,8.561,79.467,1.081,76,11.490,29.403,3.762
10,2025-11-05 04:25:17.554219,US,New York,40.713,-74.006,48.469,72.858,23.356,4.244,34.794,0.973,96,27.913,34.736,5.054
11,2025-11-05 05:25:17.554219,US,New York,40.713,-74.006,44.477,37.724,39.812,6.704,34.000,0.480,99,18.665,29.091,8.802
12,2025-11-05 06:25:17.554219,US,New York,40.713,-74.006,57.227,28.916,30.698,8.091,63.108,0.967,114,14.584,46.654,5.570
13,2025-11-05 07:25:17.554219,US,New York,40.713,-74.006,26.147,58.714,49.826,5.228,51.651,0.615,124,27.299,76.014,0.786
14,2025-11-05 08:25:17.554219,US,New York,40.713,-74.006,38.815,121.394,25.969,4.112,44.730,1.124,121,34.481,81.790,3.576
15,2025-11-05 09:25:17.554219,US,New York,40.713,-74.006,42.793,91.138,11.600,7.625,43.074,0.944,91,8.423,62.661,1.287
16,2025-11-05 10:25:17.554219,US,New York,40.713,-74.006,2.799,69.074,52.218,5.538,37.461,0.600,130,7.884,74.873,3.401
17,2025-11-05 11:25:17.554219,US,New York,40.713,-74.006,63.552,57.838,13.754,4.427,42.251,0.997,127,36.193,62.906,7.097
18,2025-11-05 12:25:17.554219,US,New York,40.713,-74.006,26.664,54.577,35.136,3.599,68.139,1.069,87,14.656,83.829,5.372

In [8]:
df.iloc[3]

timestamp      2025-11-04 21:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                               30.403
pm10                               79.951
no2                                63.536
so2                                 7.609
o3                                 31.369
co                                   0.23
aqi                                   158
temperature                         23.14
humidity                           89.153
wind_speed                          8.956
Name: 3, dtype: object

In [9]:
df.iloc[3:18] # starting idx : Ending idx ("Non-inclusive")

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
5,2025-11-04 23:25:17.554219,US,New York,40.713,-74.006,31.242,92.779,30.633,8.030,43.725,0.347,92,15.159,42.505,1.199
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
8,2025-11-05 02:25:17.554219,US,New York,40.713,-74.006,60.914,44.775,40.936,6.779,36.751,1.014,121,24.092,48.148,8.686
9,2025-11-05 03:25:17.554219,US,New York,40.713,-74.006,16.464,76.631,28.119,8.561,79.467,1.081,76,11.490,29.403,3.762
10,2025-11-05 04:25:17.554219,US,New York,40.713,-74.006,48.469,72.858,23.356,4.244,34.794,0.973,96,27.913,34.736,5.054
11,2025-11-05 05:25:17.554219,US,New York,40.713,-74.006,44.477,37.724,39.812,6.704,34.000,0.480,99,18.665,29.091,8.802
12,2025-11-05 06:25:17.554219,US,New York,40.713,-74.006,57.227,28.916,30.698,8.091,63.108,0.967,114,14.584,46.654,5.570
13,2025-11-05 07:25:17.554219,US,New York,40.713,-74.006,26.147,58.714,49.826,5.228,51.651,0.615,124,27.299,76.014,0.786
14,2025-11-05 08:25:17.554219,US,New York,40.713,-74.006,38.815,121.394,25.969,4.112,44.730,1.124,121,34.481,81.790,3.576
15,2025-11-05 09:25:17.554219,US,New York,40.713,-74.006,42.793,91.138,11.600,7.625,43.074,0.944,91,8.423,62.661,1.287
16,2025-11-05 10:25:17.554219,US,New York,40.713,-74.006,2.799,69.074,52.218,5.538,37.461,0.600,130,7.884,74.873,3.401
17,2025-11-05 11:25:17.554219,US,New York,40.713,-74.006,63.552,57.838,13.754,4.427,42.251,0.997,127,36.193,62.906,7.097

In [10]:
# 3. Select Rows & Columns
df.loc[1500, ["country", "city"]]

df.iloc[1500, [1, 2]] # Pass the index of country and city of data

country        DE
city       Berlin
Name: 1500, dtype: object

In [11]:
df.loc[0:25, ["country", "city", "latitude", "longitude"]]

   country      city  latitude  longitude
0       US  New York    40.713    -74.006
1       US  New York    40.713    -74.006
2       US  New York    40.713    -74.006
3       US  New York    40.713    -74.006
4       US  New York    40.713    -74.006
5       US  New York    40.713    -74.006
6       US  New York    40.713    -74.006
7       US  New York    40.713    -74.006
8       US  New York    40.713    -74.006
9       US  New York    40.713    -74.006
10      US  New York    40.713    -74.006
11      US  New York    40.713    -74.006
12      US  New York    40.713    -74.006
13      US  New York    40.713    -74.006
14      US  New York    40.713    -74.006
15      US  New York    40.713    -74.006
16      US  New York    40.713    -74.006
17      US  New York    40.713    -74.006
18      US  New York    40.713    -74.006
19      US  New York    40.713    -74.006
20      US  New York    40.713    -74.006
21      US  New York    40.713    -74.006
22      US  New York    40.713    -74.006
23      US  New York    40.713    -74.006
24      US  New York    40.713    -74.006
25      US  New York    40.713    -74.006

In [12]:
df.iloc[0:25, [1, 2, 3, 4]]

   country      city  latitude  longitude
0       US  New York    40.713    -74.006
1       US  New York    40.713    -74.006
2       US  New York    40.713    -74.006
3       US  New York    40.713    -74.006
4       US  New York    40.713    -74.006
5       US  New York    40.713    -74.006
6       US  New York    40.713    -74.006
7       US  New York    40.713    -74.006
8       US  New York    40.713    -74.006
9       US  New York    40.713    -74.006
10      US  New York    40.713    -74.006
11      US  New York    40.713    -74.006
12      US  New York    40.713    -74.006
13      US  New York    40.713    -74.006
14      US  New York    40.713    -74.006
15      US  New York    40.713    -74.006
16      US  New York    40.713    -74.006
17      US  New York    40.713    -74.006
18      US  New York    40.713    -74.006
19      US  New York    40.713    -74.006
20      US  New York    40.713    -74.006
21      US  New York    40.713    -74.006
22      US  New York    40.713    -74.006
23      US  New York    40.713    -74.006
24      US  New York    40.713    -74.006

In [13]:
df.iloc[0:25, 1:5]

   country      city  latitude  longitude
0       US  New York    40.713    -74.006
1       US  New York    40.713    -74.006
2       US  New York    40.713    -74.006
3       US  New York    40.713    -74.006
4       US  New York    40.713    -74.006
5       US  New York    40.713    -74.006
6       US  New York    40.713    -74.006
7       US  New York    40.713    -74.006
8       US  New York    40.713    -74.006
9       US  New York    40.713    -74.006
10      US  New York    40.713    -74.006
11      US  New York    40.713    -74.006
12      US  New York    40.713    -74.006
13      US  New York    40.713    -74.006
14      US  New York    40.713    -74.006
15      US  New York    40.713    -74.006
16      US  New York    40.713    -74.006
17      US  New York    40.713    -74.006
18      US  New York    40.713    -74.006
19      US  New York    40.713    -74.006
20      US  New York    40.713    -74.006
21      US  New York    40.713    -74.006
22      US  New York    40.713    -74.006
23      US  New York    40.713    -74.006
24      US  New York    40.713    -74.006

In [15]:
# 4. Select single scalar value - at & iat
df.at[0, "city"]

'New York'

In [19]:
df.iat[0, 2]

'New York'