In [1]:
# 1. Data Transformation

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("raw_data.csv")

df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [6]:
df2 = df.copy()
# apply()
df2["tax"] = df2["income"].apply(lambda x: "20%" if x >= 60000 else "10%")

# map()
gender_map = {"Male" : "M", "Female" : "F", "Unknown" : "U", "NaN" : "M"}

df2["gender"] = df2["gender"].map(gender_map)

# assign()
df2 = df2.assign(paying_tax = "yes")

# replace(old, new)

df2["tax"] = df2["tax"].replace("10%", "12%")

df2

    id          name   age country gender   income  tax paying_tax
0    1      John Doe  29.0     USA      M  55000.0  12%        yes
1    1      John Doe  29.0     USA      M  55000.0  12%        yes
2    2    Jane Smith   NaN  Canada      F  62000.0  20%        yes
3    3          Alex   NaN     USA      U  47000.0  12%        yes
4    4  Maria Garcia  34.0   Spain      F      NaN  12%        yes
5    5        Li Wei  27.0   China      M  51000.0  12%        yes
6    6           NaN  45.0   India      F  73000.0  20%        yes
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%        yes
8    8    Rachel Lee  29.0     USA      F  62000.0  20%        yes
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  12%        yes
10  10   Emily Davis  31.0     USA    NaN  58000.0  12%        yes