In [1]:
# 2. Data Transformation (Other Method)

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("raw_data.csv")

df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [21]:
df2 = df.copy()

# rename (columns) All Values of columns
df2.columns = ["Id", "Name", "Age", "Country", "Gender", "Income"]

# rename (columns) Specific values of columns
df2 = df2.rename(columns={"Income": "Salary"})

# rename (row) Specific values of columns
# df2 = df2.rename(index={1: "One"})

# sort_values
df2 = df2.sort_values("Salary")

# df2 = df2.sort_values(["Salary", "Age"])

# sort_index
df2 = df2.sort_index()

# reset_index
df2 = df2.reset_index()

# rank()
df2["Salary"].rank()

# Reorder Columns
df2[["Id", "Name", "Age", "Country", "Salary", "Gender"]]

    Id          Name   Age Country   Salary   Gender
0    1      John Doe  29.0     USA  55000.0     Male
1    1      John Doe  29.0     USA  55000.0     Male
2    2    Jane Smith   NaN  Canada  62000.0   Female
3    3          Alex   NaN     USA  47000.0  Unknown
4    4  Maria Garcia  34.0   Spain      NaN   Female
5    5        Li Wei  27.0   China  51000.0     Male
6    6           NaN  45.0   India  73000.0   Female
7    7    Ahmed Khan  38.0     NaN  68000.0     Male
8    8    Rachel Lee  29.0     USA  62000.0   Female
9    9   Carlos Ruiz   NaN  Mexico  45000.0     Male
10  10   Emily Davis  31.0     USA  58000.0      NaN