In [1]:
# 6. Melt & Pivot for Reshaping

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    "country": ["USA", "USA", "India", "India"],
    "year": [2020, 2021, 2020, 2021],
    "sales": [100, 120, 90, 110],
    "profit": [20, 25, 10, 22],
    # "tax": [10, 20, 30, 40]
})

df

  country  year  sales  profit
0     USA  2020    100      20
1     USA  2021    120      25
2   India  2020     90      10
3   India  2021    110      22

In [4]:
melted_df = df.melt(
    id_vars = ["country", "year"],
    value_vars = ["sales", "profit"],
    var_name = "metrics",
    value_name = "value",
)

melted_df

  country  year metrics  value
0     USA  2020   sales    100
1     USA  2021   sales    120
2   India  2020   sales     90
3   India  2021   sales    110
4     USA  2020  profit     20
5     USA  2021  profit     25
6   India  2020  profit     10
7   India  2021  profit     22

In [6]:
melted_df.pivot(
    index = ["country", "year"],
    columns = "metrics",
    values = "value"
)

metrics       profit  sales
country year
India   2020      10     90
        2021      22    110
USA     2020      20    100
        2021      25    120