In [1]:
# 8. Merge & Join Data

In [2]:
import pandas as pd

In [3]:
df_customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Adom", "Bob", "Charlie", "Dave"]
})

df_orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [2, 1, 4, 5],
    "amount": [250, 120, 103, 180]
})

pd.merge(df_customers, df_orders, on="customer_id") # Inner Join

   customer_id  name  order_id  amount
0            1  Adom       102     120
1            2   Bob       101     250
2            4  Dave       103     103

In [4]:
pd.merge(df_customers, df_orders, on="customer_id", how="left") # Left Join

   customer_id     name  order_id  amount
0            1     Adom     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   103.0

In [5]:
pd.merge(df_customers, df_orders, on="customer_id", how="right") # Righrt Join

   customer_id  name  order_id  amount
0            2   Bob       101     250
1            1  Adom       102     120
2            4  Dave       103     103
3            5   NaN       104     180

In [6]:
pd.merge(df_customers, df_orders, on="customer_id", how="outer") # Inner Join

   customer_id     name  order_id  amount
0            1     Adom     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   103.0
4            5      NaN     104.0   180.0

In [7]:
pd.merge(df_customers, df_orders)

   customer_id  name  order_id  amount
0            1  Adom       102     120
1            2   Bob       101     250
2            4  Dave       103     103